[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/home"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/contact"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/about"
  [headers.values]
    Cache-Control = "public, max-age=3600"
